[package]
name = "hello-world-rs-action"
version = "0.1.0"
authors = ["Seth Pellegrino <seth@codecopse.net>"]
edition = "2018"

[dependencies]
chrono = "0.4.13"
serde_json = "1"


[lib]
name = "mylib"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/bin.rs"
